### ISSUE TITLE
property to configure broker domain

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/kafka-service-broker-boshrelease#1]
the deploy errand should enable operator to specify broker domain (can set app name, org, missing domain)

btw: very nice work, glad to get cloudfoundry community Kafka solution :-)

**Comment by drnic** [comment]
If you have a look in the broker job spec, hopefully there are enough properties that you can override. Are these enough?

Next, we can add an additional operators/cf-deploy.yml which could expose each of these as variables. That way if you want to customize them you can pass in variables

Alternately, you can write your own bespoke operator patch file with the specific changes you want (say in your deployment pipelines). Like the operators/redis.yml example which has hard coded overrides.

**Comment by drnic** [comment]
Yes, more docs on how to do this stuff is a good idea :)

**Comment by drnic** [comment]
Broker domain is one property I think is missing. Good catch. Others?

**Comment by drnic** [comment]
@poblin-orange 

I've added `cf.routes` which passes an array of routes thru to the CF manifest. I've also added `manifests/operators/cf-app.yml` which exposes all the variables for where/how the broker cf app is deployed.

Cutting v0.5.1

**Comment by drnic** [comment]
@poblin-orange https://github.com/cloudfoundry-community/kafka-service-broker-boshrelease/releases/tag/v0.5.1

**Comment by poblin-orange** [comment]
thks @drnic 
I ll try 0.5.1 asap
other props i think of is cf security groups array (we usually limit cf apps outbound access, and need to limit access to only kafka manager).

**Comment by poblin-orange** [comment]
the ASG definitions are not in the brokers service errands.
We use terraform cloudfoundry to define ASG  globally (this separates services providers teams and paas operator control)
https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry

For our requirements, ASG name list in broker-deploy job would be enough.

**Comment by drnic** [comment]
@poblin-orange I'm sorry I'm not following. :/ If its ok, can you submit a PR with the change suggestions?

**Comment by poblin-orange** [comment]
@drnic sure, the PR will clarify
https://github.com/cloudfoundry-community/kafka-service-broker-boshrelease/pull/2
