### ISSUE TITLE
Any screenshots for installing Kafka?

### ISSUE THREAD

**Issue by manjunathgudisi** [cloudfoundry-community/kafka-service-broker-boshrelease#12]
Hi
I knew that you have mentioned that installation steps in Readme, however Im unable to understand how to do this.

What Im doing:
1. I opened terminal on my mac machine and cloned the github repo.
2. Trying to execute the installation steps on terminal (attached screenshot)

Im getting errors in the 1st command itself. So, it would be good if you provide any screenshots for the installation steps.

Thanks, Manju

![screen shot 2017-12-01 at 10 09 37 am](https://user-images.githubusercontent.com/6059076/33468117-d5470dc8-d67f-11e7-8234-220cfa724eda.jpg)

**Comment by drnic** [comment]
The `<bosh-alias>` should be replaced with the alias for your target BOSH environment.

For example, my `bosh envs` contains the following targets + aliases:

```
bosh envs
URL                         Alias
https://10.11.1.4:25555     aws-community-ohio
https://10.23.14.10:25555  bosh-lite-10
https://10.52.11.4:25555   vsphere-prod
```

So if I were to deploy to `aws-community-ohio`, then `<bosh-alias>` becomes:

```
export BOSH_ENVIRONMENT=aws-community-ohio
```

**Comment by drnic** [comment]
The instructions for deploying a BOSH environment for each CPI will include a `bosh alias-env` command https://bosh.io/docs/init.html - you use that alias name in your `export BOSH_ENVIRONMENT=alias`
