### ISSUE TITLE
How to use these release? 

### ISSUE THREAD

**Issue by akhettal** [cloudfoundry-community/kafka-service-broker-boshrelease#14]
HI,

The installation of the release was well done:
![image](https://user-images.githubusercontent.com/50481980/57515050-0a3ebc80-7312-11e9-9069-0cfe8f2ea6d5.png)
The kafka-service-broker is avaible on the CF marketplace/services : 
![image](https://user-images.githubusercontent.com/50481980/57515138-36f2d400-7312-11e9-87f9-15516d7e79e9.png)
As you can see, there are two apps bounded to the kafka broker, and the cf env draw show that kafka VCAP_SERVICES are well mentioned : 
![image](https://user-images.githubusercontent.com/50481980/57515230-6acdf980-7312-11e9-9640-c3ff7bb0091c.png)

however, when I generate application logs, no message is sent to the topic. Can you help me with this please?

Thank you

**Comment by Infra-Red** [comment]
Hi @akhettal ! Make sure that your [Application Security Groups](https://docs.cloudfoundry.org/concepts/asg.html) allow traffic from app to Kafka instances. Here is an information how to check existing ASGs https://docs.cloudfoundry.org/concepts/asg.html#viewing.

**Comment by akhettal** [comment]
Hi @Infra-Red ! Thanks for your support ! 
I create this kafka-security group and bind it to my Org/Space 
![image](https://user-images.githubusercontent.com/50481980/57517828-fac27200-7317-11e9-8caf-086e2d1a5318.png)
I still have any logs on my topic, even if i restarted my draw app :( 

There are any other configuration to do on the kafka manager or something like that? 
![image](https://user-images.githubusercontent.com/50481980/57518050-7b816e00-7318-11e9-87f7-c915bec0d68c.png)

Thanks

**Comment by ArthurHlt** [comment]
@akhettal you probably think to the behavior when your service is a syslog_drain_url (see: https://docs.cloudfoundry.org/devguide/services/log-management.html ) which is not here.
Kafka is message queuing system not a log drainer, you must use service Kafka on your cloud foundry application with a client by using credentials set in VCAP_SERVICES.

**Comment by CrisWar** [comment]
@ArthurHlt That's what we finally understood ...Now we know what we have to do !
