### ISSUE TITLE
Stemcell with Operating System 'ubuntu-trusty' doesn't exist

### ISSUE THREAD

**Issue by bstarke** [cloudfoundry-community/kafka-service-broker-boshrelease#16]
Unable to deploy on cf dev, with trusty going out of support imo xenial should be the default.

`Task 833 | 13:24:39 | Preparing deployment: Preparing deployment (00:00:00)
                    L Error: Stemcell with Operating System 'ubuntu-trusty' doesn't exist`

**Comment by drnic** [comment]
Try the patch on master.
